web/codepass_web/views/problem.py
import copy
import hashlib
import shutil
import subprocess
from .common import *

mod = Blueprint('problem', __name__)


def file_sha1(filename):
    with open(filename, 'rb') as f:
        sha1 = hashlib.sha1()
        while True:
            data = f.read(65536)
            if not data:
                break
            sha1.update(data)
    return sha1.hexdigest()


def testcase_dir(sha1):
    return '{}/{}/{}/{}/{}'.format(sha1[0:2], sha1[2:4], sha1[4:6], sha1[6:8], sha1)


@mod.route('/<int:problem_id>/')
def get_problem(problem_id):
    while True:
        problem = db.session.query(Problem).filter(Problem.id == problem_id).first()
        if not problem or not problem.archive_id:
            break
        archive = db.session.query(ProblemArchive).filter(ProblemArchive.id == problem.archive_id).one()
        return render_template('problem/show.html', problem=problem, archive=archive)
    abort(404)


@mod.route('/add')
@login_required
def get_add():
    form = FlaskForm()
    return render_template('problem/add.html', form=form)


def problem_form_to_dict(fields, form, path):
    d = {}
    for field in fields:
        key = field['key']
        if field['type'] == 'combo':
            d[key] = problem_form_to_dict(field['content'], form, path + key + '.')
        else:
            value = form.get(path + key, None)
            if value is not None:
                if field['type'] == 'int':
                    try:
                        d[key] = int(value)
                    except ValueError:
                        pass
                else:
                    d[key] = value
    return d


@mod.route('/save', methods=['POST'])
@login_required
def post_save():
    while True:
        form = FlaskForm()
        if not form.validate():
            break

        now = datetime.utcnow()
        user = db.session.query(User).filter(User.id == session['user_id']).one()

        config = problem_form_to_dict(current_app.config['WEB']['PROBLEM_FORMAT'], request.form, '')

        problem = Problem(is_public=False,
                          title=request.form.get('title', None),
                          author=request.form.get('author', None),
                          source=request.form.get('source', None),
                          updated_by=user.id,
                          updated_at=now,
                          created_by=user.id,
                          created_at=now)
        db.session.add(problem)
        db.session.commit()

        archive = ProblemArchive(problem_id=problem.id,
                                 problem_yaml=config,
                                 config_yaml={},
                                 created_by=user.id,
                                 created_at=now)
        db.session.add(archive)
        db.session.commit()

        problem.archive_id = archive.id
        db.session.commit()

        flash('The problem has been added.', 'success')
        return redirect(url_for('.get_problem', problem_id=problem.id))
    return render_template('problem/add.html', form=form)


@mod.route('/<int:problem_id>/upload')
@login_required
def get_upload(problem_id):
    problem = db.session.query(Problem).filter(Problem.id == problem_id).first()
    if not problem or not problem.archive_id:
        abort(404)
    archive = db.session.query(ProblemArchive).filter(ProblemArchive.id == problem.archive_id).one()
    form = FlaskForm()
    return render_template('problem/upload.html', form=form, problem=problem, archive=archive)


@mod.route('/<int:problem_id>/upload', methods=['POST'])
@login_required
def post_upload(problem_id):
    form = FlaskForm()
    assert form.validate()
    problem = db.session.query(Problem).filter(Problem.id == problem_id).first()
    if not problem or not problem.archive_id:
        abort(404)

    file = request.files.get('file', None)
    if not file or not file.filename:
        flash('No file uploaded', 'danger')
        return redirect(url_for('.get_upload', problem_id=problem_id))
    filename = secure_filename(file.filename)
    base, ext = os.path.splitext(filename)
    filepath = os.path.join(current_app.config['TMP_UPLOAD_DIR'], random_string(32)) + ext
    dirname = os.path.join(current_app.config['TMP_UPLOAD_DIR'], random_string(32))
    dst = os.path.join(dirname, base)
    file.save(filepath)

    os.makedirs(dst, exist_ok=True)
    p = subprocess.run(['unzip', '-o', '-d', dst, filepath], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if os.path.exists(filepath):
        os.unlink(filepath)
    if p.returncode:
        shutil.rmtree(dirname, ignore_errors=True)
        msg = 'Failed to extract the archive. <pre>STDOUT:\n{}\nSTDERR:\n{}</pre>'.format(
            str(p.stdout, 'utf-8'), str(p.stderr, 'utf-8'))
        flash(msg, 'danger')
        return redirect(url_for('.get_upload', problem_id=problem_id))

    if 'upload_testcase' not in session:
        session['upload_testcase'] = {}
    key = random_string(32)
    session['upload_testcase'][key] = {'problem_id': problem_id, 'dirname': dirname, 'filename': filename}
    flash('Successfully uploaded.', 'success')
    return redirect(url_for('.get_select_files'))


@mod.route('/select_files')
@login_required
def get_select_files():
    uploads = []
    if 'upload_testcase' in session:
        for key, upload in session['upload_testcase'].items():
            problem_id = upload['problem_id']
            dirname = upload['dirname']
            l = len(dirname) + 1
            files = [os.path.join(root[l:], file) for root, dir, files in os.walk(dirname) for file in files]
            files.sort()
            problem = db.session.query(Problem).filter(Problem.id == problem_id).one()
            uploads.append({'problem': problem, 'files': files, 'key': key, 'filename': upload['filename']})
    form = FlaskForm()
    return render_template('problem/select_files.html', uploads=uploads, form=form)


@mod.route('/select_files/<key>', methods=['POST'])
@login_required
def post_select_files(key):
    form = FlaskForm()
    assert form.validate()
    uploads = session.get('upload_testcase', None)
    if not uploads or key not in uploads:
        flash('Cannot find the uploaded files.', 'danger')
        return redirect(url_for('homepage.homepage'))

    problem_id = uploads[key]['problem_id']
    dirname = uploads[key]['dirname']
    problem = db.session.query(Problem).filter(Problem.id == problem_id).one()
    archive = db.session.query(ProblemArchive).filter(ProblemArchive.id == problem.archive_id).one()
    db.make_transient(archive)
    archive.id = None
    if 'files' not in archive.config_yaml:
        archive.config_yaml['files'] = {}

    for filename, checkbox in request.form.items():
        if checkbox != 'on':
            continue
        src_path = os.path.join(dirname, filename)
        if not os.path.exists(src_path):
            continue
        sha1 = file_sha1(src_path)
        dst_path = os.path.join(current_app.config['TESTCASES_DIR'], testcase_dir(sha1))
        os.makedirs(os.path.dirname(dst_path), exist_ok=True)
        os.rename(src_path, dst_path)
        archive.config_yaml['files'][filename] = dict(
            sha1=sha1,
            updated_at=datetime.utcnow().timestamp()
        )

    db.session.add(archive)
    db.session.commit()
    problem.archive_id = archive.id
    db.session.add(problem)
    db.session.commit()

    shutil.rmtree(dirname, ignore_errors=True)
    del uploads[key]
    flash('Successfully added files.', 'success')
    return redirect(url_for('.get_edit_testcases', problem_id=problem_id))


@mod.route('/<int:problem_id>/modify_files', methods=['POST'])
@login_required
def post_modify_files(problem_id):
    form = FlaskForm()
    assert form.validate()
    problem = db.session.query(Problem).filter(Problem.id == problem_id).first()
    if not problem or not problem.archive_id:
        abort(404)
    archive = db.session.query(ProblemArchive).filter(ProblemArchive.id == problem.archive_id).one()
    db.make_transient(archive)
    archive.id = None

    new_files = archive.config_yaml['files']
    old_files = copy.copy(new_files)
    for name, value in request.form.items():
        if not name.startswith('rename-'):
            continue
        old_name = name[len('rename-'):]
        if old_name not in old_files:
            flash('There is no file called <code>{}</code>.'.format(old_name), 'danger')
            return redirect(url_for('.get_edit_testcases', problem_id=problem_id))
        del new_files[old_name]
        new_files[value] = old_files[old_name]
    for name, value in request.form.items():
        if not name.startswith('delete-'):
            continue
        new_name = name[len('delete-'):]
        if new_name not in new_files:
            flash('There is no file called <code>{}</code>.'.format(new_name), 'danger')
            return redirect(url_for('.get_edit_testcases', problem_id=problem_id))
        del new_files[new_name]

    db.session.add(archive)
    db.session.commit()
    problem.archive_id = archive.id
    db.session.add(problem)
    db.session.commit()

    flash('Successfully updated files.', 'success')
    return redirect(url_for('.get_edit_testcases', problem_id=problem_id))


def testcase_config_do_line(cols, files):
    if len(cols) <= 0:
        return {'err': 'Standard Input is missing.'}
    stdin = cols[0].strip()
    if stdin not in files:
        return {'err': 'There is no file named <code>{}</code>.'.format(stdin)}

    if len(cols) <= 1:
        return {'err': 'Standard Output is missing.'}
    stdout = cols[1].strip()
    if stdout not in files:
        return {'err': 'There is no file named <code>{}</code>.'.format(stdout)}

    if len(cols) <= 2:
        return {'err': 'Time Limit (ms) is missing.'}
    time = cols[2].strip()
    try:
        time = int(time)
    except ValueError:
        return {'err': '<code>{}</code> is not an integer.'.format(time)}

    if len(cols) <= 3:

web/codepass_web/views/submission.py
from .common import *

mod = Blueprint('submission', __name__)


class SubmitForm(FlaskForm):
    problem_id = IntegerField('Problem ID', [InputRequired('This field is required.')])
    language_id = SelectField('Language', [InputRequired('This field is required.')], coerce=int)
    code = TextAreaField('Compile Command', [InputRequired('This field is required.')])


@mod.route('/submit/')
@mod.route('/submit/<int:problem_id>')
@login_required
def get_submit(problem_id=None):
    form = SubmitForm()
    if problem_id:
        form.problem_id.data = problem_id
    languages = db.session.query(Language).order_by(Language.id).all()
    form.language_id.choices = [(l.id, l.name) for l in languages]
    return render_template('submission/submit.html', form=form)


@mod.route('/submit/', methods=['POST'])
@login_required
def post_submit():
    form = SubmitForm()
    languages = db.session.query(Language).order_by(Language.id).all()
    form.language_id.choices = [(l.id, l.name) for l in languages]
    if not form.validate():
        return render_template('submission/submit.html', form=form)
    problem = db.session.query(Problem).filter(Problem.id == form.problem_id.data).first()
    if not problem:
        flash('Cannot find the problem {}'.format(form.problem_id.data), 'danger')
        return render_template('submission/submit.html', form=form)

    submission = Submission(user_id=session['user_id'],
                            problem_id=form.problem_id.data,
                            language_id=form.language_id.data,
                            status=constants.SUBMISSION_PENDING,
                            code=form.code.data,
                            created_at=datetime.utcnow())
    db.session.add(submission)
    db.session.commit()
    return redirect(url_for('.get_status'))


@mod.route('/status/')
def get_status():
    # TODO: paginate
    # TODO: filter
    submissions = db.session.query(Submission).order_by(Submission.id.desc()).all()
    user_ids = [s.user_id for s in submissions]
    users = {u.id: u for u in db.session.query(User).filter(User.id.in_(user_ids))}
    languages = {l.id: l for l in db.session.query(Language)}
    return render_template('submission/status.html', submissions=submissions, users=users, languages=languages)

web/codepass_web/templates/problem/_edit.html
{% extends "layout.html" %}
{% block title %}{{ _edit_page_title }}{% endblock %}
{% macro render_fields(fields, path) %}
  {% for field in fields %}
    {% if field.type == 'combo' %}
      {{ render_fields(field.content, path + field.key + '.') }}
    {% else %}
      <div class="form-group row">
        <label for="{{ path }}{{ field.key }}" class="col-sm-2 col-form-label">{{ field.title }}</label>
        <div class="col-sm-7">
          {% if field.type == 'string' %}
            <input type="text" id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}" class="form-control">
          {% elif field.type == 'int' %}
            <input type="number" id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}"
                   class="form-control monospace">
          {% elif field.type == 'markdown' %}
            <textarea id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}"
                      class="form-control monospace"></textarea>
          {% elif field.type == 'code' %}
            <textarea id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}"
                      class="form-control monospace"></textarea>
          {% endif %}
        </div>
      </div>
    {% endif %}
  {% endfor %}
{% endmacro %}
{% block content %}

  <h1>{{ _edit_page_header }}</h1>
  <hr>

  <form method="post" action="{{ url_for("problem.post_save") }}">
    {{ form.hidden_tag() }}
    {{ render_fields(config.WEB.PROBLEM_FORMAT, '') }}

    <button type="submit" class="btn btn-primary">Save</button>
  </form>

{% endblock %}

web/codepass_web/templates/problem/add.html
{% set _edit_page_title = 'Add a Problem' %}
{% set _edit_page_header = _edit_page_title %}
{% include 'problem/_edit.html' %}

web/codepass_web/templates/problem/edit.html
{% extends "layout.html" %}
{% block title %}{{ _edit_page_title }}{% endblock %}
{% macro render_fields(fields, path) %}
  {% for field in fields %}
    {% if field.type == 'combo' %}
      {{ render_fields(field.content, path + field.key + '.') }}
    {% else %}
      <div class="form-group row">
        <label for="{{ path }}{{ field.key }}" class="col-sm-2 col-form-label">{{ field.title }}</label>
        <div class="col-sm-7">
          {% if field.type == 'string' %}
            <input type="text" id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}" class="form-control">
          {% elif field.type == 'int' %}
            <input type="number" id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}"
                   class="form-control monospace">
          {% elif field.type == 'markdown' %}
            <textarea id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}"
                      class="form-control monospace"></textarea>
          {% elif field.type == 'code' %}
            <textarea id="{{ path }}{{ field.key }}" name="{{ path }}{{ field.key }}"
                      class="form-control monospace"></textarea>
          {% endif %}
        </div>
      </div>
    {% endif %}
  {% endfor %}
{% endmacro %}
{% block content %}

  <h1>{{ _edit_page_header }}</h1>
  <hr>

  <form method="post" action="{{ url_for("problem.post_save") }}">
    {{ form.hidden_tag() }}
    {{ render_fields(config.WEB.PROBLEM_FORMAT, '') }}

    <button type="submit" class="btn btn-primary">Save</button>
  </form>

{% endblock %}

web/codepass_web/templates/problem/select_files.html
{% extends "layout.html" %}
{% block title %}Select Uploaded Files{% endblock %}
{% block content %}
  <h1>Select Uploaded Files</h1>
  {% for upload in uploads %}
    <hr>
    <h2>[{{ upload.problem.id }}]{{ upload.problem.title }}
      <small><code>{{ upload.filename }}</code></small>
    </h2>
    <form method="post" action="{{ url_for('.post_select_files', key=upload.key) }}">
      {{ form.hidden_tag() }}
      {% for file in upload.files %}
        <div class="form-check">
          <input class="form-check-input" type="checkbox" checked id="{{ upload.key }}-{{ file }}" name="{{ file }}">
          <label class="form-check-label monospace" for="{{ upload.key }}-{{ file }}">{{ file }}</label>
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">Add Files</button>
    </form>
  {% endfor %}
{% endblock %}

web/codepass_web/templates/problem/show.html
{% extends "layout.html" %}
{% block title %}{{ archive.problem_yaml.title }}{% endblock %}
{% macro render_fields(fields, problem_yaml) %}
  {% for field in fields if field.key in problem_yaml %}
    {% set value = problem_yaml[field.key] %}
    {% if field.type == 'combo' %}
      {{ render_fields(field.content, value) }}
    {% elif field.key == 'title' %}
      <h1>{{ value }}</h1>
    {% elif field.type in ['string', 'int'] %}
      <pre>{{ field.title }}: {{ value }}</pre>
    {% elif field.type == 'code' %}
      <h3>{{ field.title }}</h3>
      <pre>{{ value }}</pre>
    {% elif field.type == 'markdown' %}
      <h3>{{ field.title }}</h3>
      {{ value | markdown | safe }}
    {% endif %}
  {% endfor %}
{% endmacro %}
{% block content %}
  <pre>{{ archive.problem_yaml }}</pre>
  <pre>{{ archive.config_yaml }}</pre>
  <a href="{{ url_for('.get_upload', problem_id=problem.id) }}">Upload Testcases</a>,
  <a href="{{ url_for('.get_edit_testcases', problem_id=problem.id) }}">Edit Testcases</a>
  <hr>
  {{ render_fields(config.WEB.PROBLEM_FORMAT, archive.problem_yaml) }}
  <hr>
  <a class="btn btn-primary" href="{{ url_for('submission.get_submit', problem_id=problem.id) }}">Submit</a>
{% endblock %}

web/codepass_web/templates/problem/testcases.html
{% extends "layout.html" %}
{% block title %}Configure Testcases of [{{ problem.id }}]{{ archive.problem_yaml.title }}{% endblock %}
{% block content %}
  <h1>[{{ problem.id }}]{{ archive.problem_yaml.title }}</h1>
  <h2>Configure Testcases</h2>
  <table class="table table-sm table-striped">
    <thead>
    <tr>
      <th>Standard Input</th>
      <th>Standard Output</th>
      <th>Time Limit (ms)</th>
      <th>Memory Limit (MB)</th>
      <th>Score</th>
    </tr>
    </thead>
    <tbody id="testcases">
    </tbody>
  </table>
  <form method="post" action="{{ url_for('.post_testcase_config', problem_id=problem.id) }}">
    {{ form.hidden_tag() }}
    <textarea class="form-control monospace" rows="13" name="config" id="testcase-config"
              placeholder="For Example,&#10;1.in|1.out|1000|256|10&#10;2.in|2.out|1000|256|10&#10;...">{{ testcase_config }}</textarea>
    <button type="button" class="btn btn-secondary" id="auto-fill">Auto Fill</button>
    <button type="submit" class="btn btn-primary">Save Testcases</button>
  </form>

  <hr>
  <h2>All Files</h2>
  <form method="post" action="{{ url_for('.post_modify_files', problem_id=problem.id) }}">
    {{ form.hidden_tag() }}
    <table class="table table-sm">
      <thead>
      <tr>
        <th>Delete</th>
        <th>Rename</th>
        <th>Updated At</th>
      </tr>
      </thead>
      <tbody id="all-files">
      </tbody>
    </table>
    <button type="submit" class="btn btn-primary">Delete/Rename</button>
  </form>
{% endblock %}
{% block scripts %}
  <script src="{{ url_for('static', filename='config_testcases.js') }}"></script>
  <script>
      let files = {
          {% for k, v in archive.config_yaml.files.items() %}
              '{{ k }}': {sha1: '{{ v.sha1 }}', updated_at: {{ v.updated_at }}},
          {%- endfor %}
      };
      config_testcases(files, {{ archive.problem_yaml.time_limit }}, {{ archive.problem_yaml.memory_limit }});
  </script>
{% endblock %}

web/codepass_web/templates/problem/upload.html
{% extends "layout.html" %}
{% block title %}Upload Testcases of {{ archive.problem_yaml.title }}{% endblock %}
{% block content %}
  <h1>[{{ problem.id }}]{{ archive.problem_yaml.title }} <small>Upload Testcases</small></h1>
  <hr>
  <form method="post" enctype="multipart/form-data" action="{{ url_for('.post_upload', problem_id=problem.id) }}">
    {{ form.hidden_tag() }}
    <div class="form-group row">
      <label for="file" class="col-sm-2 col-form-label">Select File</label>
      <div class="col-sm-7"><input type="file" id="file" name="file" class="form-control-file"></div>
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
{% endblock %}